


spring:
  datasource:
    url: jdbc:h2:~/userdb
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 772838225854-demm2e8av94r6r8jjm4b770ctkqpgreg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
